"""
Investment Portfolio Dashboard
Tracks P/L of current holdings against the latest fetched ticker prices.

Run:
    streamlit run app.py

Data sources:
    ../ticker_fetcher/ticker_data_YYYYMMDD.csv  — generated by fetch_tickers.py
    holdings.csv                                 — your positions (edit in sidebar)
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from datetime import date

# ── Page setup ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Portfolio Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Paths ─────────────────────────────────────────────────────────────────────
DASHBOARD_DIR = Path(__file__).parent
FETCHER_DIR   = DASHBOARD_DIR.parent / "ticker_fetcher"
HOLDINGS_FILE = DASHBOARD_DIR / "holdings.csv"

ACCOUNT_OPTIONS = ["Brokerage", "IRA", "Roth IRA", "401k", "Other"]
HOLDINGS_COLS   = ["ticker", "shares", "avg_cost", "purchase_date", "account", "notes"]

STALE_THRESHOLD_DAYS = 3   # calendar days before data is considered stale


# ── Data loaders ──────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def load_prices() -> tuple:
    """
    Finds and loads the most-recently dated ticker CSV from the fetcher folder.
    Returns (DataFrame | None, filename | None, file_date | None).
    """
    csvs = sorted(FETCHER_DIR.glob("ticker_data_*.csv"), reverse=True)
    if not csvs:
        return None, None, None

    path = csvs[0]
    df   = pd.read_csv(path)
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

    # Parse date from filename: ticker_data_YYYYMMDD.csv
    stem = path.stem  # e.g. "ticker_data_20260527"
    try:
        fdate = date(int(stem[-8:-4]), int(stem[-4:-2]), int(stem[-2:]))
    except Exception:
        fdate = None

    return df, path.name, fdate


def latest_close(prices_df: pd.DataFrame, ticker: str) -> float | None:
    """Return the most recent Close price for a ticker (OK rows only)."""
    mask = (
        (prices_df["Ticker"].str.upper() == ticker.upper())
        & prices_df["fetch_status"].str.startswith("OK", na=False)
    )
    rows = prices_df[mask]
    if rows.empty:
        return None
    try:
        return float(rows.sort_values("Date").iloc[-1]["Close"])
    except Exception:
        return None


def load_holdings() -> pd.DataFrame:
    """Load holdings.csv; create it with headers only if missing."""
    if not HOLDINGS_FILE.exists():
        empty = pd.DataFrame(columns=HOLDINGS_COLS)
        empty.to_csv(HOLDINGS_FILE, index=False)
        return empty

    df = pd.read_csv(HOLDINGS_FILE, dtype=str)
    df["shares"]        = pd.to_numeric(df["shares"],   errors="coerce").fillna(0)
    df["avg_cost"]      = pd.to_numeric(df["avg_cost"], errors="coerce").fillna(0)
    df["ticker"]        = df["ticker"].astype(str).str.strip().str.upper()
    # DateColumn requires actual date objects, not strings
    df["purchase_date"] = pd.to_datetime(df["purchase_date"], errors="coerce").dt.date

    # Guarantee all expected columns exist
    for col in HOLDINGS_COLS:
        if col not in df.columns:
            df[col] = ""

    return df[HOLDINGS_COLS]


def save_holdings(df: pd.DataFrame) -> None:
    save_df = df.copy()
    # Convert date objects back to "YYYY-MM-DD" strings for CSV storage
    if "purchase_date" in save_df.columns:
        save_df["purchase_date"] = pd.to_datetime(
            save_df["purchase_date"], errors="coerce"
        ).apply(lambda d: d.strftime("%Y-%m-%d") if not pd.isnull(d) else "")
    save_df.to_csv(HOLDINGS_FILE, index=False)


# ── Portfolio calculator ───────────────────────────────────────────────────────

def build_portfolio(holdings: pd.DataFrame, prices_df) -> pd.DataFrame:
    """
    Aggregate all lots per ticker, attach current prices, compute P/L.
    Returns one row per ticker.
    """
    if holdings.empty:
        return pd.DataFrame()

    rows = []
    for ticker, group in holdings.groupby("ticker"):
        total_shares = group["shares"].sum()
        if total_shares <= 0:
            continue

        wavg_cost = (group["shares"] * group["avg_cost"]).sum() / total_shares
        accts = ", ".join(
            sorted({str(a) for a in group["account"].dropna() if str(a).strip() and str(a) != "nan"})
        )
        lots = len(group)

        cur_px   = latest_close(prices_df, ticker) if prices_df is not None else None
        cost     = total_shares * wavg_cost
        mkt_val  = total_shares * cur_px if cur_px is not None else None
        pl_d     = mkt_val - cost if mkt_val is not None else None
        pl_pct   = pl_d / cost * 100 if (cost > 0 and pl_d is not None) else None

        rows.append({
            "Ticker":        ticker,
            "Lots":          lots,
            "Shares":        total_shares,
            "Avg Cost":      wavg_cost,
            "Current Price": cur_px,
            "Cost Basis":    cost,
            "Market Value":  mkt_val,
            "P/L $":         pl_d,
            "P/L %":         pl_pct,
            "Account(s)":    accts,
            "_has_price":    cur_px is not None,
        })

    return pd.DataFrame(rows)


# ── Styling ───────────────────────────────────────────────────────────────────

def _pl_color(val) -> str:
    """Return CSS string for positive/negative P/L values."""
    try:
        v = float(val)
    except (TypeError, ValueError):
        return ""
    if v > 0:
        return "color: #27ae60; font-weight: 600"
    if v < 0:
        return "color: #e74c3c; font-weight: 600"
    return ""


def style_table(df: pd.DataFrame):
    display_cols = [
        c for c in
        ["Ticker", "Lots", "Shares", "Avg Cost", "Current Price",
         "Cost Basis", "Market Value", "P/L $", "P/L %", "Account(s)"]
        if c in df.columns
    ]
    display = df[display_cols].copy()

    fmt = {
        "Lots":          "{:,d}",
        # Strip trailing zeros so "26.00000" shows as "26", "3.15781" stays "3.15781"
        "Shares":        lambda v: f"{v:,.5f}".rstrip("0").rstrip(".") if pd.notna(v) else "—",
        "Avg Cost":      "${:,.2f}",
        "Current Price": lambda v: f"${v:,.2f}" if pd.notna(v) else "—",
        "Cost Basis":    "${:,.2f}",
        "Market Value":  lambda v: f"${v:,.2f}" if pd.notna(v) else "—",
        "P/L $":         lambda v: f"${v:+,.2f}" if pd.notna(v) else "—",
        "P/L %":         lambda v: f"{v:+.2f}%" if pd.notna(v) else "—",
    }
    # Only format columns that exist in the display
    fmt = {k: v for k, v in fmt.items() if k in display_cols}

    styler = display.style.format(fmt, na_rep="—")

    # Support both pandas <2.1 (applymap) and >=2.1 (map)
    pl_cols = [c for c in ["P/L $", "P/L %"] if c in display_cols]
    if pl_cols:
        _apply = getattr(styler, "map", getattr(styler, "applymap", None))
        if _apply:
            styler = _apply(_pl_color, subset=pl_cols)

    right_cols = [c for c in ["Shares","Avg Cost","Current Price","Cost Basis","Market Value","P/L $","P/L %","Lots"] if c in display_cols]
    left_cols  = [c for c in ["Ticker","Account(s)"] if c in display_cols]
    if right_cols:
        styler = styler.set_properties(**{"text-align": "right"}, subset=right_cols)
    if left_cols:
        styler = styler.set_properties(**{"text-align": "left"},  subset=left_cols)

    return styler


# ── Sidebar ───────────────────────────────────────────────────────────────────

def render_sidebar(holdings: pd.DataFrame, price_file, price_date) -> pd.DataFrame | None:
    """Render the sidebar editor. Returns edited DataFrame if Save was clicked, else None."""
    with st.sidebar:
        st.title("⚙️ Manage Holdings")

        # --- Price data freshness ---
        st.markdown("---")
        st.subheader("📂 Price Data Source")
        if price_file:
            st.caption(f"`{price_file}`")
            if price_date:
                gap = (date.today() - price_date).days
                if gap <= STALE_THRESHOLD_DAYS:
                    st.success(f"✅ Fresh — {price_date}")
                else:
                    st.warning(
                        f"⚠️ Stale — {gap} days old ({price_date})\n\n"
                        f"Re-run `fetch_tickers.py` in `ticker_fetcher/`"
                    )
        else:
            st.error(
                f"No price CSV found in `{FETCHER_DIR.name}/`.\n\n"
                "Run `fetch_tickers.py` first."
            )

        # --- Holdings editor ---
        st.markdown("---")
        st.subheader("📋 Edit Positions")
        st.caption(
            "• Click **+** to add a row  \n"
            "• Click the 🗑 icon to delete a row  \n"
            "• Edit any cell inline  \n"
            "• Click **Save** to apply changes"
        )

        edited = st.data_editor(
            holdings,
            num_rows="dynamic",
            use_container_width=True,
            column_order=HOLDINGS_COLS,
            column_config={
                "ticker":        st.column_config.TextColumn(
                    "Ticker", max_chars=15, help="Stock symbol e.g. NVDA, VTI"
                ),
                "shares":        st.column_config.NumberColumn(
                    "Shares", min_value=0.00001, format="%.5f", step=0.00001,
                    help="Fractional shares supported — minimum 0.00001"
                ),
                "avg_cost":      st.column_config.NumberColumn(
                    "Avg Cost ($)", min_value=0.01, format="%.2f", step=0.01,
                    help="Your average purchase price per share"
                ),
                "purchase_date": st.column_config.DateColumn(
                    "Buy Date", format="YYYY-MM-DD",
                    help="Date of first/most recent purchase"
                ),
                "account":       st.column_config.SelectboxColumn(
                    "Account", options=ACCOUNT_OPTIONS
                ),
                "notes":         st.column_config.TextColumn("Notes"),
            },
            key="holdings_editor",
        )

        col_save, col_dl = st.columns(2)
        saved = False

        with col_save:
            if st.button("💾 Save", use_container_width=True, type="primary"):
                clean = edited.copy()
                clean["ticker"] = clean["ticker"].astype(str).str.strip().str.upper()
                clean = clean[
                    clean["ticker"].notna()
                    & (clean["ticker"].str.len() > 0)
                    & (clean["ticker"] != "NAN")
                ]
                save_holdings(clean)
                st.cache_data.clear()
                st.success("✅ Saved!")
                saved = True

        with col_dl:
            csv_bytes = holdings.to_csv(index=False).encode()
            st.download_button(
                "⬇ Export CSV",
                data=csv_bytes,
                file_name="holdings.csv",
                mime="text/csv",
                use_container_width=True,
            )

        if saved:
            st.rerun()

    return None


# ── Main app ──────────────────────────────────────────────────────────────────

def main():
    prices_df, price_file, price_date = load_prices()
    holdings = load_holdings()

    render_sidebar(holdings, price_file, price_date)

    # ── Header ────────────────────────────────────────────────────────────────
    st.title("📈 Investment Portfolio Dashboard")
    st.caption(
        f"Today: **{date.today().strftime('%B %d, %Y')}**  "
        f"•  Price source: `{price_file or 'None'}`"
    )

    if holdings.empty:
        st.info("👈 No holdings yet. Add positions in the sidebar to get started.")
        return

    port = build_portfolio(holdings, prices_df)

    if port.empty:
        st.warning("Holdings loaded but all rows have zero shares — check your data.")
        return

    # ── Summary metrics ───────────────────────────────────────────────────────
    priced_port = port[port["_has_price"]]
    no_price    = port[~port["_has_price"]]

    total_cost_all  = port["Cost Basis"].sum()
    total_cost_prcd = priced_port["Cost Basis"].sum()
    total_mkt       = priced_port["Market Value"].sum() if not priced_port.empty else None
    total_pl_d      = (total_mkt - total_cost_prcd) if total_mkt is not None else None
    total_pl_p      = (total_pl_d / total_cost_prcd * 100
                       if (total_pl_d is not None and total_cost_prcd > 0) else None)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric(
        "💰 Total Cost Basis",
        f"${total_cost_all:,.2f}",
        help="Sum of (shares × avg cost) across all holdings"
    )
    c2.metric(
        "📊 Market Value",
        f"${total_mkt:,.2f}" if total_mkt is not None else "N/A",
        help="Based on tickers with available price data"
    )
    c3.metric(
        "📈 Total P/L $",
        f"${total_pl_d:+,.2f}" if total_pl_d is not None else "N/A",
        delta=f"{total_pl_d:+,.2f}" if total_pl_d is not None else None,
    )
    c4.metric(
        "📉 Total P/L %",
        f"{total_pl_p:+.2f}%" if total_pl_p is not None else "N/A",
        delta=f"{total_pl_p:+.2f}%" if total_pl_p is not None else None,
    )

    # Warn about missing prices
    if not no_price.empty:
        missing = no_price["Ticker"].tolist()
        st.warning(
            f"⚠️ No price data for: **{', '.join(missing)}**. "
            "Ensure these are in `tickers.txt` and re-run `fetch_tickers.py`."
        )

    st.markdown("---")

    # ── Holdings table ────────────────────────────────────────────────────────
    st.subheader("📋 Holdings Detail")

    # Sort controls
    sort_col, sort_dir = st.columns([2, 1])
    with sort_col:
        sort_by = st.selectbox(
            "Sort by",
            options=["Ticker", "Market Value", "P/L $", "P/L %", "Cost Basis"],
            index=0,
            label_visibility="collapsed",
        )
    with sort_dir:
        ascending = st.toggle("Ascending", value=True)

    display_port = port.sort_values(sort_by, ascending=ascending, na_position="last")
    row_height   = max(80 + 35 * len(display_port), 150)

    st.dataframe(
        style_table(display_port),
        use_container_width=True,
        hide_index=True,
        height=min(row_height, 650),
    )

    st.markdown("---")

    # ── Charts ────────────────────────────────────────────────────────────────
    chart_data = port.dropna(subset=["Market Value"])

    if chart_data.empty:
        st.info("Charts require price data. Run `fetch_tickers.py` first.")
        return

    # Row 1: Allocation pie  |  P/L $ bar
    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("🥧 Portfolio Allocation")
        alloc_by = st.radio(
            "Value basis",
            ["Market Value", "Cost Basis"],
            horizontal=True,
            key="alloc_radio",
        )
        pie_source = chart_data if alloc_by == "Market Value" else port
        fig_pie = px.pie(
            pie_source,
            values=alloc_by,
            names="Ticker",
            hole=0.42,
            color_discrete_sequence=px.colors.qualitative.Pastel,
        )
        fig_pie.update_traces(textposition="inside", textinfo="percent+label")
        fig_pie.update_layout(
            margin=dict(t=20, b=10, l=10, r=10),
            height=400,
            showlegend=False,
        )
        st.plotly_chart(fig_pie, use_container_width=True)

    with col_right:
        st.subheader("💵 P/L $ per Ticker")
        bar_data = port.dropna(subset=["P/L $"]).sort_values("P/L $")
        fig_bar  = go.Figure(go.Bar(
            x=bar_data["Ticker"],
            y=bar_data["P/L $"],
            marker_color=["#27ae60" if v >= 0 else "#e74c3c" for v in bar_data["P/L $"]],
            text=[f"${v:+,.2f}" for v in bar_data["P/L $"]],
            textposition="outside",
            textfont=dict(size=11),
        ))
        fig_bar.update_layout(
            xaxis_title=None,
            yaxis_title="Unrealised P/L ($)",
            yaxis=dict(zeroline=True, zerolinewidth=1.5, zerolinecolor="#aaa"),
            margin=dict(t=20, b=20, l=20, r=20),
            height=400,
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    # Row 2: P/L % bar (full width)
    st.subheader("📊 P/L % per Ticker")
    pct_data  = port.dropna(subset=["P/L %"]).sort_values("P/L %")
    fig_pct   = go.Figure(go.Bar(
        x=pct_data["Ticker"],
        y=pct_data["P/L %"],
        marker_color=["#27ae60" if v >= 0 else "#e74c3c" for v in pct_data["P/L %"]],
        text=[f"{v:+.1f}%" for v in pct_data["P/L %"]],
        textposition="outside",
        textfont=dict(size=11),
    ))
    fig_pct.update_layout(
        xaxis_title=None,
        yaxis_title="Unrealised P/L (%)",
        yaxis=dict(zeroline=True, zerolinewidth=1.5, zerolinecolor="#aaa"),
        margin=dict(t=20, b=20, l=20, r=20),
        height=380,
    )
    st.plotly_chart(fig_pct, use_container_width=True)


if __name__ == "__main__":
    main()
