"""
Investment Portfolio Dashboard
Tracks P/L of current holdings against the latest fetched ticker prices.

Run:
    streamlit run app.py

Pages (sidebar navigation):
  📈 Portfolio    — P/L dashboard for your holdings
  📊 Market Data  — Browse every ticker in the price CSV with charts

Data sources:
    ../ticker_fetcher/ticker_data_YYYYMMDD.csv  — generated by fetch_tickers.py
    holdings.csv                                 — your positions (edit in sidebar)

Multiple portfolios:
    Add a "portfolio" column to holdings.csv.  Each row belongs to the named
    portfolio; blank rows default to "Default".  The dashboard creates one tab
    per portfolio plus a combined "All Portfolios" tab.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from datetime import date

# ── Page setup ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Portfolio Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Paths & constants ─────────────────────────────────────────────────────────
DASHBOARD_DIR = Path(__file__).parent
FETCHER_DIR   = DASHBOARD_DIR.parent / "ticker_fetcher"
HOLDINGS_FILE = DASHBOARD_DIR / "holdings.csv"

ACCOUNT_OPTIONS      = ["Brokerage", "IRA", "Roth IRA", "401k", "Other"]
HOLDINGS_COLS        = ["ticker", "shares", "avg_cost", "purchase_date",
                         "account", "portfolio", "notes"]
STALE_THRESHOLD_DAYS = 3
PALETTE = px.colors.qualitative.Pastel   # stable palette shared across charts


# ── Data loaders ──────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def load_prices() -> tuple:
    """Find and load the most-recently dated ticker CSV from the fetcher folder."""
    csvs = sorted(FETCHER_DIR.glob("ticker_data_*.csv"), reverse=True)
    if not csvs:
        return None, None, None
    path = csvs[0]
    df   = pd.read_csv(path)
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    stem = path.stem  # ticker_data_YYYYMMDD
    try:
        fdate = date(int(stem[-8:-4]), int(stem[-4:-2]), int(stem[-2:]))
    except Exception:
        fdate = None
    return df, path.name, fdate


def latest_close(prices_df: pd.DataFrame, ticker: str) -> float | None:
    """Return the most recent Close price for a ticker (OK rows only)."""
    mask = (
        (prices_df["Ticker"].str.upper() == ticker.upper())
        & prices_df["fetch_status"].str.startswith("OK", na=False)
    )
    rows = prices_df[mask]
    if rows.empty:
        return None
    try:
        return float(rows.sort_values("Date").iloc[-1]["Close"])
    except Exception:
        return None


def load_holdings() -> pd.DataFrame:
    """Load holdings.csv; create it with headers only if missing."""
    if not HOLDINGS_FILE.exists():
        empty = pd.DataFrame(columns=HOLDINGS_COLS)
        empty.to_csv(HOLDINGS_FILE, index=False)
        return empty

    df = pd.read_csv(HOLDINGS_FILE, dtype=str)
    df["shares"]        = pd.to_numeric(df.get("shares"),   errors="coerce").fillna(0)
    df["avg_cost"]      = pd.to_numeric(df.get("avg_cost"), errors="coerce").fillna(0)
    df["ticker"]        = df["ticker"].astype(str).str.strip().str.upper()
    df["purchase_date"] = pd.to_datetime(
        df.get("purchase_date"), errors="coerce"
    ).dt.date
    df["portfolio"] = (
        df["portfolio"].fillna("").astype(str).str.strip().replace("", "Default")
        if "portfolio" in df.columns
        else "Default"
    )
    for col in HOLDINGS_COLS:
        if col not in df.columns:
            df[col] = ""
    return df[HOLDINGS_COLS]


def save_holdings(df: pd.DataFrame) -> None:
    save_df = df.copy()
    if "purchase_date" in save_df.columns:
        save_df["purchase_date"] = pd.to_datetime(
            save_df["purchase_date"], errors="coerce"
        ).apply(lambda d: d.strftime("%Y-%m-%d") if not pd.isnull(d) else "")
    save_df.to_csv(HOLDINGS_FILE, index=False)


# ── Market data analysis ──────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def build_market_summary(prices_df) -> pd.DataFrame:
    """
    Build a one-row-per-ticker summary from the price CSV.
    Handles any number of tickers and any date range (1 mo, 6 mo, 1 yr, …).
    Tickers with ERROR status appear with N/A price columns.
    """
    if prices_df is None or (isinstance(prices_df, pd.DataFrame) and prices_df.empty):
        return pd.DataFrame()

    rows = []
    for ticker, grp in prices_df.groupby("Ticker", sort=True):
        ok = grp[grp["fetch_status"].str.startswith("OK", na=False)].copy()
        raw_status = grp["fetch_status"].iloc[0]

        if ok.empty or ok["Date"].isna().all():
            rows.append({
                "Ticker":       ticker,
                "Status":       raw_status,
                "Trading Days": 0,
                "Date Range":   "—",
                "Latest Close": None,
                "Period High":  None,
                "Period Low":   None,
                "_has_data":    False,
            })
            continue

        ok     = ok.dropna(subset=["Date"]).sort_values("Date")
        d_from = ok["Date"].iloc[0].date()
        d_to   = ok["Date"].iloc[-1].date()

        # Cross-year check: show year on both sides when different
        if d_from.year == d_to.year:
            date_range = f"{d_from.strftime('%d %b')} – {d_to.strftime('%d %b %y')}"
        else:
            date_range = f"{d_from.strftime('%d %b %y')} – {d_to.strftime('%d %b %y')}"

        rows.append({
            "Ticker":       ticker,
            "Status":       raw_status,
            "Trading Days": len(ok),
            "Date Range":   date_range,
            "Latest Close": float(ok["Close"].iloc[-1]),
            "Period High":  float(ok["High"].max()) if "High" in ok.columns else float(ok["Close"].max()),
            "Period Low":   float(ok["Low"].min())  if "Low"  in ok.columns else float(ok["Close"].min()),
            "_has_data":    True,
        })

    return pd.DataFrame(rows)


# ── Portfolio calculator ───────────────────────────────────────────────────────

def build_portfolio(
    holdings: pd.DataFrame,
    prices_df,
    portfolio_filter: str | None = None,
) -> pd.DataFrame:
    """
    Aggregate lots, attach current prices, compute P/L.

    portfolio_filter=None  → group by (Portfolio, Ticker) — "All Portfolios" view
    portfolio_filter="X"   → filter to X, then group by Ticker — single-portfolio view
    Always returns a "Portfolio" column.
    """
    if holdings.empty:
        return pd.DataFrame()

    src = (holdings if portfolio_filter is None
           else holdings[holdings["portfolio"] == portfolio_filter])
    if src.empty:
        return pd.DataFrame()

    multi_key = portfolio_filter is None
    group_by  = ["portfolio", "ticker"] if multi_key else "ticker"

    rows = []
    for keys, group in src.groupby(group_by, sort=True):
        if multi_key:
            pf_name, ticker = keys
        else:
            ticker  = keys
            pf_name = portfolio_filter

        total_shares = group["shares"].sum()
        if total_shares < 0.00001:
            continue

        wavg_cost = (group["shares"] * group["avg_cost"]).sum() / total_shares
        accts = ", ".join(
            sorted({str(a) for a in group["account"].dropna()
                    if str(a).strip() and str(a) != "nan"})
        )
        cur_px  = latest_close(prices_df, ticker) if prices_df is not None else None
        cost    = total_shares * wavg_cost
        mkt_val = total_shares * cur_px if cur_px is not None else None
        pl_d    = mkt_val - cost if mkt_val is not None else None
        pl_pct  = pl_d / cost * 100 if (cost > 0 and pl_d is not None) else None

        rows.append({
            "Portfolio":     pf_name,
            "Ticker":        ticker,
            "Lots":          len(group),
            "Shares":        total_shares,
            "Avg Cost":      wavg_cost,
            "Current Price": cur_px,
            "Cost Basis":    cost,
            "Market Value":  mkt_val,
            "P/L $":         pl_d,
            "P/L %":         pl_pct,
            "Account(s)":    accts,
            "_has_price":    cur_px is not None,
        })

    return pd.DataFrame(rows)


def portfolio_summary(port: pd.DataFrame) -> pd.DataFrame:
    """Roll up per-(portfolio, ticker) rows to one summary row per portfolio."""
    rows = []
    for pf, grp in port.groupby("Portfolio"):
        priced    = grp[grp["_has_price"]]
        cost_all  = grp["Cost Basis"].sum()
        cost_prcd = priced["Cost Basis"].sum()
        mkt       = priced["Market Value"].sum() if not priced.empty else None
        pl_d      = (mkt - cost_prcd) if mkt is not None else None
        pl_pct    = (pl_d / cost_prcd * 100
                     if (pl_d is not None and cost_prcd > 0) else None)
        rows.append({
            "Portfolio":    pf,
            "Positions":    len(grp),
            "Cost Basis":   cost_all,
            "Market Value": mkt,
            "P/L $":        pl_d,
            "P/L %":        pl_pct,
        })
    return pd.DataFrame(rows)


# ── Styling helpers ───────────────────────────────────────────────────────────

def _pl_color(val) -> str:
    try:
        v = float(val)
    except (TypeError, ValueError):
        return ""
    if v > 0:
        return "color: #27ae60; font-weight: 600"
    if v < 0:
        return "color: #e74c3c; font-weight: 600"
    return ""


def _apply_pl_color(styler, cols: list[str]):
    """Apply _pl_color — compatible with pandas <2.1 (applymap) and >=2.1 (map)."""
    valid = [c for c in cols if c in styler.data.columns]
    if not valid:
        return styler
    fn = getattr(styler, "map", getattr(styler, "applymap", None))
    return fn(_pl_color, subset=valid) if fn else styler


_MONEY_FMT = "${:,.2f}"
_SHARES_FMT = lambda v: f"{v:,.5f}".rstrip("0").rstrip(".") if pd.notna(v) else "—"
_OPT_MONEY  = lambda v: f"${v:,.2f}" if pd.notna(v) else "—"
_PL_D_FMT   = lambda v: f"${v:+,.2f}" if pd.notna(v) else "—"
_PL_P_FMT   = lambda v: f"{v:+.2f}%" if pd.notna(v) else "—"


def style_table(df: pd.DataFrame, show_portfolio: bool = False):
    col_order = [
        "Portfolio", "Ticker", "Lots", "Shares", "Avg Cost",
        "Current Price", "Cost Basis", "Market Value", "P/L $", "P/L %", "Account(s)",
    ]
    if not show_portfolio:
        col_order = [c for c in col_order if c != "Portfolio"]
    display_cols = [c for c in col_order if c in df.columns]
    display      = df[display_cols].copy()

    fmt = {
        "Lots":          "{:,d}",
        "Shares":        _SHARES_FMT,
        "Avg Cost":      _MONEY_FMT,
        "Current Price": _OPT_MONEY,
        "Cost Basis":    _MONEY_FMT,
        "Market Value":  _OPT_MONEY,
        "P/L $":         _PL_D_FMT,
        "P/L %":         _PL_P_FMT,
    }
    fmt    = {k: v for k, v in fmt.items() if k in display_cols}
    styler = display.style.format(fmt, na_rep="—")
    styler = _apply_pl_color(styler, ["P/L $", "P/L %"])

    right = [c for c in ["Lots","Shares","Avg Cost","Current Price",
                          "Cost Basis","Market Value","P/L $","P/L %"]
             if c in display_cols]
    left  = [c for c in ["Portfolio","Ticker","Account(s)"] if c in display_cols]
    if right: styler = styler.set_properties(**{"text-align": "right"}, subset=right)
    if left:  styler = styler.set_properties(**{"text-align": "left"},  subset=left)
    return styler


def style_summary(df: pd.DataFrame):
    fmt = {
        "Positions":    "{:,d}",
        "Cost Basis":   _MONEY_FMT,
        "Market Value": _OPT_MONEY,
        "P/L $":        _PL_D_FMT,
        "P/L %":        _PL_P_FMT,
    }
    fmt    = {k: v for k, v in fmt.items() if k in df.columns}
    styler = df.style.format(fmt, na_rep="—")
    styler = _apply_pl_color(styler, ["P/L $", "P/L %"])
    return styler


def style_market_summary(df: pd.DataFrame):
    """Style the market-data summary table; colour-code the Status column."""
    fmt = {
        "Latest Close": _OPT_MONEY,
        "Period High":  _OPT_MONEY,
        "Period Low":   _OPT_MONEY,
    }
    fmt    = {k: v for k, v in fmt.items() if k in df.columns}
    styler = df.style.format(fmt, na_rep="—")

    def _status_color(val) -> str:
        s = str(val)
        if s == "OK":
            return "color: #27ae60; font-weight: 600"
        if s.startswith("OK|"):
            return "color: #f39c12; font-weight: 600"   # warning (STALE/SHORT)
        if s == "ERROR":
            return "color: #e74c3c; font-weight: 600"
        return ""

    fn = getattr(styler, "map", getattr(styler, "applymap", None))
    if fn and "Status" in df.columns:
        styler = fn(_status_color, subset=["Status"])

    right = [c for c in ["Trading Days","Latest Close","Period High","Period Low"]
             if c in df.columns]
    left  = [c for c in ["Ticker","Status","Date Range"] if c in df.columns]
    if right: styler = styler.set_properties(**{"text-align": "right"}, subset=right)
    if left:  styler = styler.set_properties(**{"text-align": "left"},  subset=left)
    return styler


# ── Ticker chart renderer ─────────────────────────────────────────────────────

def render_ticker_chart(ok_df: pd.DataFrame, ticker: str, key_suffix: str) -> None:
    """
    Renders a mini stats row + a toggle-able Line / Candlestick chart
    for a single ticker.  key_suffix must be unique per ticker.
    """
    # Stats row
    latest   = float(ok_df["Close"].iloc[-1])
    p_high   = float(ok_df["High"].max()) if "High" in ok_df.columns else float(ok_df["Close"].max())
    p_low    = float(ok_df["Low"].min())  if "Low"  in ok_df.columns else float(ok_df["Close"].min())
    rng      = p_high - p_low
    rng_pct  = rng / p_low * 100 if p_low > 0 else 0

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Latest Close", f"${latest:,.2f}")
    m2.metric("Period High",  f"${p_high:,.2f}")
    m3.metric("Period Low",   f"${p_low:,.2f}")
    m4.metric("Period Range", f"${rng:,.2f}", f"{rng_pct:.1f}%")

    # Chart type toggle
    chart_type = st.radio(
        "Chart type",
        ["📈 Line (Close)", "🕯 Candlestick"],
        horizontal=True,
        key=f"ctype_{key_suffix}",
        label_visibility="collapsed",
    )

    if chart_type == "📈 Line (Close)":
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=ok_df["Date"],
            y=ok_df["Close"],
            mode="lines",
            name="Close",
            line=dict(color="#3498db", width=2),
            fill="tozeroy",
            fillcolor="rgba(52,152,219,0.08)",
            hovertemplate="%{x|%d %b %y}<br>Close: $%{y:,.2f}<extra></extra>",
        ))
        # Period high / low reference lines
        fig.add_hline(
            y=p_high,
            line=dict(color="#27ae60", width=1, dash="dot"),
            annotation_text=f"High ${p_high:,.2f}",
            annotation_position="top right",
        )
        fig.add_hline(
            y=p_low,
            line=dict(color="#e74c3c", width=1, dash="dot"),
            annotation_text=f"Low ${p_low:,.2f}",
            annotation_position="bottom right",
        )
    else:
        # Candlestick
        fig = go.Figure(go.Candlestick(
            x=ok_df["Date"],
            open=ok_df["Open"]  if "Open"  in ok_df.columns else ok_df["Close"],
            high=ok_df["High"]  if "High"  in ok_df.columns else ok_df["Close"],
            low=ok_df["Low"]    if "Low"   in ok_df.columns else ok_df["Close"],
            close=ok_df["Close"],
            name=ticker,
            increasing_line_color="#27ae60",
            decreasing_line_color="#e74c3c",
            hovertext=ok_df["Date"].dt.strftime("%d %b %y"),
        ))

    fig.update_layout(
        xaxis_title=None,
        yaxis_title="Price ($)",
        yaxis=dict(tickprefix="$", tickformat=",.2f"),
        xaxis_rangeslider_visible=False,
        margin=dict(t=30, b=20, l=10, r=90),
        height=380,
        hovermode="x unified",
    )
    st.plotly_chart(fig, use_container_width=True, key=f"chart_{key_suffix}")


# ── Market Data page ──────────────────────────────────────────────────────────

def render_market_data_page(prices_df, price_file: str | None, price_date) -> None:
    st.header("📊 Market Data")

    if prices_df is None:
        st.error(
            f"No price CSV found in `{FETCHER_DIR.name}/`.  "
            "Run `fetch_tickers.py` first."
        )
        return

    # ── File info banner ──────────────────────────────────────────────────────
    ticker_count = prices_df["Ticker"].nunique()
    if price_date:
        gap       = (date.today() - price_date).days
        freshness = "✅ Fresh" if gap <= STALE_THRESHOLD_DAYS else f"⚠️ Stale ({gap}d old)"
        st.caption(
            f"Source: `{price_file}` — **{ticker_count} tickers** — {freshness}"
        )

    summary = build_market_summary(prices_df)
    if summary.empty:
        st.warning("Could not build summary — check the price CSV format.")
        return

    # ── Summary table ─────────────────────────────────────────────────────────
    st.subheader("📋 Ticker Summary")
    st.caption(
        "Click any column header to sort.  "
        "Green = OK, orange = OK with warnings (STALE/SHORT), red = ERROR."
    )
    display_cols = [c for c in
                    ["Ticker","Status","Trading Days","Date Range",
                     "Latest Close","Period High","Period Low"]
                    if c in summary.columns]

    st.dataframe(
        style_market_summary(summary[display_cols]),
        use_container_width=True,
        hide_index=True,
        height=min(80 + 35 * len(summary), 600),
    )

    st.markdown("---")

    # ── Per-ticker expandable charts ──────────────────────────────────────────
    st.subheader("📈 Ticker Charts")
    st.caption("Expand a ticker to view its price history. Toggle between Line and Candlestick.")

    has_data = summary[summary["_has_data"]]
    no_data  = summary[~summary["_has_data"]]

    for _, row in has_data.iterrows():
        ticker = row["Ticker"]
        # Pull only OK rows for this ticker, sorted by date
        ok_df  = prices_df[
            (prices_df["Ticker"] == ticker)
            & prices_df["fetch_status"].str.startswith("OK", na=False)
        ].dropna(subset=["Date"]).sort_values("Date").copy()

        if ok_df.empty:
            continue

        label = (
            f"{ticker}   "
            f"Close ${row['Latest Close']:,.2f}  ·  "
            f"High ${row['Period High']:,.2f}  ·  "
            f"Low ${row['Period Low']:,.2f}  ·  "
            f"{row['Date Range']}  ({row['Trading Days']} days)"
        )
        with st.expander(label, expanded=False):
            render_ticker_chart(ok_df, ticker, key_suffix=ticker)

    # Error tickers (collapsed, grouped)
    if not no_data.empty:
        with st.expander(
            f"❌ {len(no_data)} ticker(s) with no data / ERROR", expanded=False
        ):
            for _, row in no_data.iterrows():
                st.write(f"**{row['Ticker']}** — `{row['Status']}`")


# ── Portfolio view helpers ────────────────────────────────────────────────────

def _portfolio_color_map(port: pd.DataFrame) -> dict[str, str]:
    pfs = sorted(port["Portfolio"].dropna().unique().tolist())
    return {pf: PALETTE[i % len(PALETTE)] for i, pf in enumerate(pfs)}


def render_view(port: pd.DataFrame, show_portfolio: bool, key_suffix: str) -> None:
    """Render metrics, sortable holdings table, and charts for any portfolio slice."""
    if port.empty:
        st.info("No holdings to display.")
        return

    priced    = port[port["_has_price"]]
    no_price  = port[~port["_has_price"]]
    cost_all  = port["Cost Basis"].sum()
    cost_prcd = priced["Cost Basis"].sum()
    total_mkt = priced["Market Value"].sum() if not priced.empty else None
    total_pl_d = (total_mkt - cost_prcd) if total_mkt is not None else None
    total_pl_p = (total_pl_d / cost_prcd * 100
                  if (total_pl_d is not None and cost_prcd > 0) else None)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("💰 Cost Basis",   f"${cost_all:,.2f}",
              help="Shares × avg cost, all positions")
    c2.metric("📊 Market Value",
              f"${total_mkt:,.2f}"   if total_mkt  is not None else "N/A",
              help="Priced positions only")
    c3.metric("📈 P/L $",
              f"${total_pl_d:+,.2f}" if total_pl_d is not None else "N/A",
              delta=f"{total_pl_d:+,.2f}" if total_pl_d is not None else None)
    c4.metric("📉 P/L %",
              f"{total_pl_p:+.2f}%"  if total_pl_p is not None else "N/A",
              delta=f"{total_pl_p:+.2f}%" if total_pl_p is not None else None)

    if not no_price.empty:
        st.warning(
            f"⚠️ No price data for: **{', '.join(no_price['Ticker'].tolist())}**. "
            "Check `tickers.txt` and re-run `fetch_tickers.py`."
        )

    st.markdown("---")

    # Holdings table
    st.subheader("📋 Holdings")
    sort_opts = (["Portfolio","Ticker"] if show_portfolio else ["Ticker"]) + \
                ["Market Value","P/L $","P/L %","Cost Basis","Shares"]
    sc, sd = st.columns([2, 1])
    with sc:
        sort_by = st.selectbox("Sort by", sort_opts, index=0,
                               label_visibility="collapsed",
                               key=f"sort_{key_suffix}")
    with sd:
        asc = st.toggle("Ascending", value=True, key=f"asc_{key_suffix}")

    display_port = port.sort_values(sort_by, ascending=asc, na_position="last")
    st.dataframe(
        style_table(display_port, show_portfolio=show_portfolio),
        use_container_width=True,
        hide_index=True,
        height=min(max(80 + 35 * len(display_port), 150), 650),
    )

    st.markdown("---")

    # Charts
    chart_data = port.dropna(subset=["Market Value"])
    if chart_data.empty:
        st.info("Charts require price data — run `fetch_tickers.py` first.")
        return

    color_map = _portfolio_color_map(port) if show_portfolio else {}

    col_l, col_r = st.columns(2)

    # Allocation pie
    with col_l:
        st.subheader("🥧 Allocation")
        if show_portfolio:
            r1, r2 = st.columns(2)
            with r1:
                alloc_by  = st.radio("Basis", ["Market Value", "Cost Basis"],
                                     horizontal=False, key=f"alloc_basis_{key_suffix}")
            with r2:
                group_dim = st.radio("Group by", ["Ticker", "Portfolio"],
                                     horizontal=False, key=f"alloc_grp_{key_suffix}")
        else:
            alloc_by  = st.radio("Basis", ["Market Value", "Cost Basis"],
                                 horizontal=True, key=f"alloc_basis_{key_suffix}")
            group_dim = "Ticker"

        pie_src = chart_data if alloc_by == "Market Value" else port
        if group_dim == "Portfolio":
            pie_df    = pie_src.groupby("Portfolio", as_index=False).agg({alloc_by: "sum"})
            names_col = "Portfolio"
        else:
            pie_df    = pie_src
            names_col = "Ticker"

        fig_pie = px.pie(
            pie_df, values=alloc_by, names=names_col,
            hole=0.42, color_discrete_sequence=PALETTE,
        )
        fig_pie.update_traces(textposition="inside", textinfo="percent+label")
        fig_pie.update_layout(
            margin=dict(t=10,b=10,l=10,r=10), height=380, showlegend=False
        )
        st.plotly_chart(fig_pie, use_container_width=True, key=f"pie_{key_suffix}")

    # P/L $ bar
    with col_r:
        st.subheader("💵 P/L $ per Ticker")
        bar_data   = port.dropna(subset=["P/L $"]).sort_values("P/L $")
        bar_colors = (
            [color_map.get(pf, "#888") for pf in bar_data["Portfolio"]]
            if show_portfolio
            else ["#27ae60" if v >= 0 else "#e74c3c" for v in bar_data["P/L $"]]
        )
        fig_bar = go.Figure(go.Bar(
            x=bar_data["Ticker"], y=bar_data["P/L $"],
            marker_color=bar_colors,
            text=[f"${v:+,.2f}" for v in bar_data["P/L $"]],
            textposition="outside", textfont=dict(size=10),
        ))
        fig_bar.update_layout(
            xaxis_title=None, yaxis_title="Unrealised P/L ($)",
            yaxis=dict(zeroline=True, zerolinewidth=1.5, zerolinecolor="#aaa"),
            margin=dict(t=10,b=20,l=20,r=20), height=380,
        )
        st.plotly_chart(fig_bar, use_container_width=True, key=f"bar_{key_suffix}")

    # P/L % bar (full width)
    st.subheader("📊 P/L % per Ticker")
    pct_data   = port.dropna(subset=["P/L %"]).sort_values("P/L %")
    pct_colors = (
        [color_map.get(pf, "#888") for pf in pct_data["Portfolio"]]
        if show_portfolio
        else ["#27ae60" if v >= 0 else "#e74c3c" for v in pct_data["P/L %"]]
    )
    fig_pct = go.Figure(go.Bar(
        x=pct_data["Ticker"], y=pct_data["P/L %"],
        marker_color=pct_colors,
        text=[f"{v:+.1f}%" for v in pct_data["P/L %"]],
        textposition="outside", textfont=dict(size=10),
    ))
    fig_pct.update_layout(
        xaxis_title=None, yaxis_title="Unrealised P/L (%)",
        yaxis=dict(zeroline=True, zerolinewidth=1.5, zerolinecolor="#aaa"),
        margin=dict(t=10,b=20,l=20,r=50), height=350,
    )
    st.plotly_chart(fig_pct, use_container_width=True, key=f"pct_{key_suffix}")


# ── Sidebar ───────────────────────────────────────────────────────────────────

def render_sidebar(holdings: pd.DataFrame, price_file, price_date) -> str:
    """Render the sidebar and return the selected page name."""
    with st.sidebar:
        # ── Page navigation ───────────────────────────────────────────────────
        page = st.radio(
            "Page",
            ["📈 Portfolio", "📊 Market Data"],
            horizontal=True,
            label_visibility="collapsed",
            key="nav",
        )

        # ── Price data freshness ──────────────────────────────────────────────
        st.markdown("---")
        st.subheader("📂 Price Data Source")
        if price_file:
            st.caption(f"`{price_file}`")
            if price_date:
                gap = (date.today() - price_date).days
                if gap <= STALE_THRESHOLD_DAYS:
                    st.success(f"✅ Fresh — {price_date}")
                else:
                    st.warning(
                        f"⚠️ Stale — {gap} days old ({price_date})\n\n"
                        f"Re-run `fetch_tickers.py` in `ticker_fetcher/`"
                    )
        else:
            st.error(
                f"No price CSV in `{FETCHER_DIR.name}/`.\n\n"
                "Run `fetch_tickers.py` first."
            )

        # ── Holdings editor (Portfolio page only) ─────────────────────────────
        if page == "📈 Portfolio":
            st.markdown("---")
            st.subheader("📋 Edit Positions")
            existing_pfs = sorted(
                {str(p) for p in holdings["portfolio"].dropna()
                 if str(p).strip() and str(p) != "nan"}
            )
            pf_hint = ", ".join(existing_pfs) if existing_pfs else "e.g. Growth, Core"
            st.caption(
                "• **+** to add a row  •  🗑 to delete  •  Edit inline  \n"
                f"• **Portfolio** — current: `{pf_hint}`  \n"
                "• Blank portfolio → `Default`  \n"
                "• Click **Save** when done"
            )

            edited = st.data_editor(
                holdings,
                num_rows="dynamic",
                use_container_width=True,
                column_order=HOLDINGS_COLS,
                column_config={
                    "ticker":        st.column_config.TextColumn(
                        "Ticker", max_chars=15, help="Symbol e.g. NVDA, VTI"
                    ),
                    "shares":        st.column_config.NumberColumn(
                        "Shares", min_value=0.00001, format="%.5f", step=0.00001,
                        help="Fractional shares — min 0.00001"
                    ),
                    "avg_cost":      st.column_config.NumberColumn(
                        "Avg Cost ($)", min_value=0.01, format="%.2f", step=0.01
                    ),
                    "purchase_date": st.column_config.DateColumn(
                        "Buy Date", format="YYYY-MM-DD"
                    ),
                    "account":       st.column_config.SelectboxColumn(
                        "Account", options=ACCOUNT_OPTIONS
                    ),
                    "portfolio":     st.column_config.TextColumn(
                        "Portfolio", max_chars=30,
                        help="Groups positions into separate tabs. Blank → 'Default'."
                    ),
                    "notes":         st.column_config.TextColumn("Notes"),
                },
                key="holdings_editor",
            )

            col_save, col_dl = st.columns(2)
            saved = False

            with col_save:
                if st.button("💾 Save", use_container_width=True, type="primary"):
                    clean = edited.copy()
                    clean["ticker"] = clean["ticker"].astype(str).str.strip().str.upper()
                    clean["portfolio"] = (
                        clean["portfolio"].fillna("").astype(str).str.strip()
                        .replace("", "Default")
                    )
                    clean = clean[
                        clean["ticker"].notna()
                        & (clean["ticker"].str.len() > 0)
                        & (clean["ticker"] != "NAN")
                    ]
                    save_holdings(clean)
                    st.cache_data.clear()
                    st.success("✅ Saved!")
                    saved = True

            with col_dl:
                st.download_button(
                    "⬇ Export",
                    data=holdings.to_csv(index=False).encode(),
                    file_name="holdings.csv",
                    mime="text/csv",
                    use_container_width=True,
                )

            if saved:
                st.rerun()

    return page


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    prices_df, price_file, price_date = load_prices()
    holdings = load_holdings()

    page = render_sidebar(holdings, price_file, price_date)

    # ════════════════════════════════════════════════════════════════════════
    # PAGE: Market Data
    # ════════════════════════════════════════════════════════════════════════
    if page == "📊 Market Data":
        render_market_data_page(prices_df, price_file, price_date)
        return

    # ════════════════════════════════════════════════════════════════════════
    # PAGE: Portfolio
    # ════════════════════════════════════════════════════════════════════════
    st.title("📈 Investment Portfolio Dashboard")
    st.caption(
        f"Today: **{date.today().strftime('%B %d, %Y')}**  •  "
        f"Price source: `{price_file or 'None'}`"
    )

    if holdings.empty:
        st.info("👈 No holdings yet — add positions in the sidebar.")
        return

    portfolios = sorted(holdings["portfolio"].dropna().unique().tolist())
    port_all   = build_portfolio(holdings, prices_df)

    if port_all.empty:
        st.warning("All rows have zero shares — check your holdings data.")
        return

    tab_labels = ["📊 All Portfolios"] + [f"📁 {p}" for p in portfolios]
    tabs       = st.tabs(tab_labels)

    with tabs[0]:
        if len(portfolios) > 1:
            st.subheader("📂 Portfolio Breakdown")
            summ = portfolio_summary(port_all)
            st.dataframe(
                style_summary(summ),
                use_container_width=True,
                hide_index=True,
                height=50 + 35 * len(summ),
            )
            st.markdown("---")
        render_view(
            port_all,
            show_portfolio=len(portfolios) > 1,
            key_suffix="all",
        )

    for i, pf in enumerate(portfolios):
        with tabs[i + 1]:
            port_pf = build_portfolio(holdings, prices_df, portfolio_filter=pf)
            render_view(port_pf, show_portfolio=False, key_suffix=f"pf_{i}")


if __name__ == "__main__":
    main()
