"""
Investment Portfolio Dashboard
Tracks P/L of current holdings against the latest fetched ticker prices.

Run:
    streamlit run app.py

Data sources:
    ../ticker_fetcher/ticker_data_YYYYMMDD.csv  — generated by fetch_tickers.py
    holdings.csv                                 — your positions (edit in sidebar)

Multiple portfolios:
    Add a "portfolio" column to holdings.csv.  Each row belongs to the named
    portfolio; blank rows default to "Default".  The dashboard creates one tab
    per portfolio plus a combined "All Portfolios" tab.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from datetime import date

# ── Page setup ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Portfolio Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Paths & constants ─────────────────────────────────────────────────────────
DASHBOARD_DIR = Path(__file__).parent
FETCHER_DIR   = DASHBOARD_DIR.parent / "ticker_fetcher"
HOLDINGS_FILE = DASHBOARD_DIR / "holdings.csv"

ACCOUNT_OPTIONS      = ["Brokerage", "IRA", "Roth IRA", "401k", "Other"]
HOLDINGS_COLS        = ["ticker", "shares", "avg_cost", "purchase_date",
                         "account", "portfolio", "notes"]
STALE_THRESHOLD_DAYS = 3
# Stable colour palette shared across charts (portfolio colours are assigned
# alphabetically so they stay consistent across tabs)
PALETTE = px.colors.qualitative.Pastel


# ── Data loaders ──────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def load_prices() -> tuple:
    """Find and load the most-recently dated ticker CSV from the fetcher folder."""
    csvs = sorted(FETCHER_DIR.glob("ticker_data_*.csv"), reverse=True)
    if not csvs:
        return None, None, None
    path = csvs[0]
    df   = pd.read_csv(path)
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    stem = path.stem  # ticker_data_YYYYMMDD
    try:
        fdate = date(int(stem[-8:-4]), int(stem[-4:-2]), int(stem[-2:]))
    except Exception:
        fdate = None
    return df, path.name, fdate


def latest_close(prices_df: pd.DataFrame, ticker: str) -> float | None:
    """Return the most recent Close price for a ticker (OK rows only)."""
    mask = (
        (prices_df["Ticker"].str.upper() == ticker.upper())
        & prices_df["fetch_status"].str.startswith("OK", na=False)
    )
    rows = prices_df[mask]
    if rows.empty:
        return None
    try:
        return float(rows.sort_values("Date").iloc[-1]["Close"])
    except Exception:
        return None


def load_holdings() -> pd.DataFrame:
    """Load holdings.csv; create it with headers only if missing."""
    if not HOLDINGS_FILE.exists():
        empty = pd.DataFrame(columns=HOLDINGS_COLS)
        empty.to_csv(HOLDINGS_FILE, index=False)
        return empty

    df = pd.read_csv(HOLDINGS_FILE, dtype=str)
    df["shares"]        = pd.to_numeric(df.get("shares"),   errors="coerce").fillna(0)
    df["avg_cost"]      = pd.to_numeric(df.get("avg_cost"), errors="coerce").fillna(0)
    df["ticker"]        = df["ticker"].astype(str).str.strip().str.upper()
    # DateColumn requires date objects, not strings
    df["purchase_date"] = pd.to_datetime(
        df.get("purchase_date"), errors="coerce"
    ).dt.date
    # Normalise portfolio: blank / NaN → "Default"
    df["portfolio"] = (
        df["portfolio"].fillna("").astype(str).str.strip().replace("", "Default")
        if "portfolio" in df.columns
        else "Default"
    )

    # Guarantee all expected columns exist
    for col in HOLDINGS_COLS:
        if col not in df.columns:
            df[col] = ""

    return df[HOLDINGS_COLS]


def save_holdings(df: pd.DataFrame) -> None:
    save_df = df.copy()
    # Convert date objects back to ISO strings for CSV storage
    if "purchase_date" in save_df.columns:
        save_df["purchase_date"] = pd.to_datetime(
            save_df["purchase_date"], errors="coerce"
        ).apply(lambda d: d.strftime("%Y-%m-%d") if not pd.isnull(d) else "")
    save_df.to_csv(HOLDINGS_FILE, index=False)


# ── Portfolio calculator ───────────────────────────────────────────────────────

def build_portfolio(
    holdings: pd.DataFrame,
    prices_df,
    portfolio_filter: str | None = None,
) -> pd.DataFrame:
    """
    Aggregate lots, attach current prices, compute P/L.

    portfolio_filter=None  → group by (Portfolio, Ticker) — "All Portfolios" view
    portfolio_filter="X"   → filter to X, then group by Ticker — single-portfolio view
    Always returns a "Portfolio" column.
    """
    if holdings.empty:
        return pd.DataFrame()

    src = (holdings if portfolio_filter is None
           else holdings[holdings["portfolio"] == portfolio_filter])
    if src.empty:
        return pd.DataFrame()

    multi_key = portfolio_filter is None
    group_by  = ["portfolio", "ticker"] if multi_key else "ticker"

    rows = []
    for keys, group in src.groupby(group_by, sort=True):
        if multi_key:
            pf_name, ticker = keys  # tuple from multi-column groupby
        else:
            ticker  = keys          # scalar from single-column groupby
            pf_name = portfolio_filter

        total_shares = group["shares"].sum()
        if total_shares < 0.00001:
            continue

        wavg_cost = (group["shares"] * group["avg_cost"]).sum() / total_shares
        accts = ", ".join(
            sorted({str(a) for a in group["account"].dropna()
                    if str(a).strip() and str(a) != "nan"})
        )
        cur_px  = latest_close(prices_df, ticker) if prices_df is not None else None
        cost    = total_shares * wavg_cost
        mkt_val = total_shares * cur_px if cur_px is not None else None
        pl_d    = mkt_val - cost if mkt_val is not None else None
        pl_pct  = pl_d / cost * 100 if (cost > 0 and pl_d is not None) else None

        rows.append({
            "Portfolio":     pf_name,
            "Ticker":        ticker,
            "Lots":          len(group),
            "Shares":        total_shares,
            "Avg Cost":      wavg_cost,
            "Current Price": cur_px,
            "Cost Basis":    cost,
            "Market Value":  mkt_val,
            "P/L $":         pl_d,
            "P/L %":         pl_pct,
            "Account(s)":    accts,
            "_has_price":    cur_px is not None,
        })

    return pd.DataFrame(rows)


def portfolio_summary(port: pd.DataFrame) -> pd.DataFrame:
    """Roll up per-(portfolio, ticker) rows to one summary row per portfolio."""
    rows = []
    for pf, grp in port.groupby("Portfolio"):
        priced    = grp[grp["_has_price"]]
        cost_all  = grp["Cost Basis"].sum()
        cost_prcd = priced["Cost Basis"].sum()
        mkt       = priced["Market Value"].sum() if not priced.empty else None
        pl_d      = (mkt - cost_prcd) if mkt is not None else None
        pl_pct    = (pl_d / cost_prcd * 100
                     if (pl_d is not None and cost_prcd > 0) else None)
        rows.append({
            "Portfolio":    pf,
            "Positions":    len(grp),
            "Cost Basis":   cost_all,
            "Market Value": mkt,
            "P/L $":        pl_d,
            "P/L %":        pl_pct,
        })
    return pd.DataFrame(rows)


# ── Styling ───────────────────────────────────────────────────────────────────

def _pl_color(val) -> str:
    try:
        v = float(val)
    except (TypeError, ValueError):
        return ""
    if v > 0:
        return "color: #27ae60; font-weight: 600"
    if v < 0:
        return "color: #e74c3c; font-weight: 600"
    return ""


def _apply_pl_color(styler, cols: list[str]):
    """Apply _pl_color compatible with both pandas <2.1 (applymap) and >=2.1 (map)."""
    valid = [c for c in cols if c in styler.data.columns]
    if not valid:
        return styler
    fn = getattr(styler, "map", getattr(styler, "applymap", None))
    return fn(_pl_color, subset=valid) if fn else styler


_MONEY_FMT    = "${:,.2f}"
_SHARES_FMT   = lambda v: f"{v:,.5f}".rstrip("0").rstrip(".") if pd.notna(v) else "—"
_OPT_MONEY    = lambda v: f"${v:,.2f}" if pd.notna(v) else "—"
_PL_D_FMT     = lambda v: f"${v:+,.2f}" if pd.notna(v) else "—"
_PL_P_FMT     = lambda v: f"{v:+.2f}%" if pd.notna(v) else "—"


def style_table(df: pd.DataFrame, show_portfolio: bool = False):
    """Style the main holdings table."""
    col_order = [
        "Portfolio", "Ticker", "Lots", "Shares", "Avg Cost",
        "Current Price", "Cost Basis", "Market Value", "P/L $", "P/L %", "Account(s)",
    ]
    if not show_portfolio:
        col_order = [c for c in col_order if c != "Portfolio"]
    display_cols = [c for c in col_order if c in df.columns]
    display      = df[display_cols].copy()

    fmt = {
        "Lots":          "{:,d}",
        "Shares":        _SHARES_FMT,
        "Avg Cost":      _MONEY_FMT,
        "Current Price": _OPT_MONEY,
        "Cost Basis":    _MONEY_FMT,
        "Market Value":  _OPT_MONEY,
        "P/L $":         _PL_D_FMT,
        "P/L %":         _PL_P_FMT,
    }
    fmt    = {k: v for k, v in fmt.items() if k in display_cols}
    styler = display.style.format(fmt, na_rep="—")
    styler = _apply_pl_color(styler, ["P/L $", "P/L %"])

    right = [c for c in ["Lots","Shares","Avg Cost","Current Price",
                          "Cost Basis","Market Value","P/L $","P/L %"]
             if c in display_cols]
    left  = [c for c in ["Portfolio","Ticker","Account(s)"] if c in display_cols]
    if right: styler = styler.set_properties(**{"text-align": "right"}, subset=right)
    if left:  styler = styler.set_properties(**{"text-align": "left"},  subset=left)

    return styler


def style_summary(df: pd.DataFrame):
    """Style the per-portfolio summary table in the All tab."""
    fmt = {
        "Positions":    "{:,d}",
        "Cost Basis":   _MONEY_FMT,
        "Market Value": _OPT_MONEY,
        "P/L $":        _PL_D_FMT,
        "P/L %":        _PL_P_FMT,
    }
    fmt    = {k: v for k, v in fmt.items() if k in df.columns}
    styler = df.style.format(fmt, na_rep="—")
    styler = _apply_pl_color(styler, ["P/L $", "P/L %"])
    return styler


# ── Shared view renderer ──────────────────────────────────────────────────────

def _portfolio_color_map(port: pd.DataFrame) -> dict[str, str]:
    """Assign a stable palette colour to each portfolio (alphabetical order)."""
    pfs = sorted(port["Portfolio"].dropna().unique().tolist())
    return {pf: PALETTE[i % len(PALETTE)] for i, pf in enumerate(pfs)}


def render_view(port: pd.DataFrame, show_portfolio: bool, key_suffix: str) -> None:
    """
    Render metrics cards, sortable holdings table, and charts.

    show_portfolio=True   → show Portfolio column; colour bars by portfolio
    show_portfolio=False  → hide Portfolio column; colour P/L bars green/red
    key_suffix            → unique string to avoid Streamlit widget-key clashes
                            between tabs (e.g. "all", "pf_0", "pf_1")
    """
    if port.empty:
        st.info("No holdings to display.")
        return

    priced    = port[port["_has_price"]]
    no_price  = port[~port["_has_price"]]
    cost_all  = port["Cost Basis"].sum()
    cost_prcd = priced["Cost Basis"].sum()
    total_mkt = priced["Market Value"].sum() if not priced.empty else None
    total_pl_d = (total_mkt - cost_prcd) if total_mkt is not None else None
    total_pl_p = (total_pl_d / cost_prcd * 100
                  if (total_pl_d is not None and cost_prcd > 0) else None)

    # ── Metrics ───────────────────────────────────────────────────────────────
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("💰 Cost Basis",   f"${cost_all:,.2f}",
              help="Shares × avg cost, all positions")
    c2.metric("📊 Market Value",
              f"${total_mkt:,.2f}"   if total_mkt  is not None else "N/A",
              help="Priced positions only")
    c3.metric("📈 P/L $",
              f"${total_pl_d:+,.2f}" if total_pl_d is not None else "N/A",
              delta=f"{total_pl_d:+,.2f}" if total_pl_d is not None else None)
    c4.metric("📉 P/L %",
              f"{total_pl_p:+.2f}%"  if total_pl_p is not None else "N/A",
              delta=f"{total_pl_p:+.2f}%" if total_pl_p is not None else None)

    if not no_price.empty:
        st.warning(
            f"⚠️ No price data for: **{', '.join(no_price['Ticker'].tolist())}**. "
            "Check `tickers.txt` and re-run `fetch_tickers.py`."
        )

    st.markdown("---")

    # ── Holdings table ────────────────────────────────────────────────────────
    st.subheader("📋 Holdings")
    sort_opts = (["Portfolio", "Ticker"] if show_portfolio else ["Ticker"]) + \
                ["Market Value", "P/L $", "P/L %", "Cost Basis", "Shares"]
    sc, sd = st.columns([2, 1])
    with sc:
        sort_by = st.selectbox("Sort by", sort_opts, index=0,
                               label_visibility="collapsed",
                               key=f"sort_{key_suffix}")
    with sd:
        asc = st.toggle("Ascending", value=True, key=f"asc_{key_suffix}")

    display_port = port.sort_values(sort_by, ascending=asc, na_position="last")
    st.dataframe(
        style_table(display_port, show_portfolio=show_portfolio),
        use_container_width=True,
        hide_index=True,
        height=min(max(80 + 35 * len(display_port), 150), 650),
    )

    st.markdown("---")

    # ── Charts ────────────────────────────────────────────────────────────────
    chart_data = port.dropna(subset=["Market Value"])
    if chart_data.empty:
        st.info("Charts require price data — run `fetch_tickers.py` first.")
        return

    # Stable colour map for the portfolio dimension
    color_map = _portfolio_color_map(port) if show_portfolio else {}

    col_l, col_r = st.columns(2)

    # Allocation pie ──────────────────────────────────────────────────────────
    with col_l:
        st.subheader("🥧 Allocation")
        if show_portfolio:
            r1, r2 = st.columns(2)
            with r1:
                alloc_by  = st.radio("Basis", ["Market Value", "Cost Basis"],
                                     horizontal=False,
                                     key=f"alloc_basis_{key_suffix}")
            with r2:
                group_dim = st.radio("Group by", ["Ticker", "Portfolio"],
                                     horizontal=False,
                                     key=f"alloc_grp_{key_suffix}")
        else:
            alloc_by  = st.radio("Basis", ["Market Value", "Cost Basis"],
                                 horizontal=True,
                                 key=f"alloc_basis_{key_suffix}")
            group_dim = "Ticker"

        pie_src   = chart_data if alloc_by == "Market Value" else port
        if group_dim == "Portfolio":
            pie_df    = pie_src.groupby("Portfolio", as_index=False).agg(
                {alloc_by: "sum"}
            )
            names_col = "Portfolio"
        else:
            pie_df    = pie_src
            names_col = "Ticker"

        fig_pie = px.pie(
            pie_df, values=alloc_by, names=names_col,
            hole=0.42, color_discrete_sequence=PALETTE,
        )
        fig_pie.update_traces(textposition="inside", textinfo="percent+label")
        fig_pie.update_layout(
            margin=dict(t=10, b=10, l=10, r=10), height=380, showlegend=False
        )
        st.plotly_chart(fig_pie, use_container_width=True)

    # P/L $ bar ───────────────────────────────────────────────────────────────
    with col_r:
        st.subheader("💵 P/L $ per Ticker")
        bar_data   = port.dropna(subset=["P/L $"]).sort_values("P/L $")
        bar_colors = (
            [color_map.get(pf, "#888") for pf in bar_data["Portfolio"]]
            if show_portfolio
            else ["#27ae60" if v >= 0 else "#e74c3c" for v in bar_data["P/L $"]]
        )
        fig_bar = go.Figure(go.Bar(
            x=bar_data["Ticker"],
            y=bar_data["P/L $"],
            marker_color=bar_colors,
            text=[f"${v:+,.2f}" for v in bar_data["P/L $"]],
            textposition="outside",
            textfont=dict(size=10),
        ))
        fig_bar.update_layout(
            xaxis_title=None,
            yaxis_title="Unrealised P/L ($)",
            yaxis=dict(zeroline=True, zerolinewidth=1.5, zerolinecolor="#aaa"),
            margin=dict(t=10, b=20, l=20, r=20),
            height=380,
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    # P/L % bar (full width) ──────────────────────────────────────────────────
    st.subheader("📊 P/L % per Ticker")
    pct_data   = port.dropna(subset=["P/L %"]).sort_values("P/L %")
    pct_colors = (
        [color_map.get(pf, "#888") for pf in pct_data["Portfolio"]]
        if show_portfolio
        else ["#27ae60" if v >= 0 else "#e74c3c" for v in pct_data["P/L %"]]
    )
    fig_pct = go.Figure(go.Bar(
        x=pct_data["Ticker"],
        y=pct_data["P/L %"],
        marker_color=pct_colors,
        text=[f"{v:+.1f}%" for v in pct_data["P/L %"]],
        textposition="outside",
        textfont=dict(size=10),
    ))
    fig_pct.update_layout(
        xaxis_title=None,
        yaxis_title="Unrealised P/L (%)",
        yaxis=dict(zeroline=True, zerolinewidth=1.5, zerolinecolor="#aaa"),
        margin=dict(t=10, b=20, l=20, r=50),
        height=350,
    )
    st.plotly_chart(fig_pct, use_container_width=True)


# ── Sidebar ───────────────────────────────────────────────────────────────────

def render_sidebar(holdings: pd.DataFrame, price_file, price_date) -> None:
    with st.sidebar:
        st.title("⚙️ Manage Holdings")

        # --- Price data freshness ---
        st.markdown("---")
        st.subheader("📂 Price Data Source")
        if price_file:
            st.caption(f"`{price_file}`")
            if price_date:
                gap = (date.today() - price_date).days
                if gap <= STALE_THRESHOLD_DAYS:
                    st.success(f"✅ Fresh — {price_date}")
                else:
                    st.warning(
                        f"⚠️ Stale — {gap} days old ({price_date})\n\n"
                        f"Re-run `fetch_tickers.py` in `ticker_fetcher/`"
                    )
        else:
            st.error(
                f"No price CSV in `{FETCHER_DIR.name}/`.\n\n"
                "Run `fetch_tickers.py` first."
            )

        # --- Holdings editor ---
        st.markdown("---")
        st.subheader("📋 Edit Positions")
        existing_pfs = sorted(
            {str(p) for p in holdings["portfolio"].dropna()
             if str(p).strip() and str(p) != "nan"}
        )
        pf_hint = ", ".join(existing_pfs) if existing_pfs else "e.g. Growth, Core"
        st.caption(
            "• **+** to add a row  •  🗑 to delete  •  Edit inline  \n"
            f"• **Portfolio** — current: `{pf_hint}`  \n"
            "• Blank portfolio → `Default`  \n"
            "• Click **Save** when done"
        )

        edited = st.data_editor(
            holdings,
            num_rows="dynamic",
            use_container_width=True,
            column_order=HOLDINGS_COLS,
            column_config={
                "ticker":        st.column_config.TextColumn(
                    "Ticker", max_chars=15, help="Symbol e.g. NVDA, VTI"
                ),
                "shares":        st.column_config.NumberColumn(
                    "Shares", min_value=0.00001, format="%.5f", step=0.00001,
                    help="Fractional shares — min 0.00001"
                ),
                "avg_cost":      st.column_config.NumberColumn(
                    "Avg Cost ($)", min_value=0.01, format="%.2f", step=0.01
                ),
                "purchase_date": st.column_config.DateColumn(
                    "Buy Date", format="YYYY-MM-DD"
                ),
                "account":       st.column_config.SelectboxColumn(
                    "Account", options=ACCOUNT_OPTIONS
                ),
                "portfolio":     st.column_config.TextColumn(
                    "Portfolio", max_chars=30,
                    help="Groups positions into separate tabs. Leave blank for 'Default'."
                ),
                "notes":         st.column_config.TextColumn("Notes"),
            },
            key="holdings_editor",
        )

        col_save, col_dl = st.columns(2)
        saved = False

        with col_save:
            if st.button("💾 Save", use_container_width=True, type="primary"):
                clean = edited.copy()
                clean["ticker"] = clean["ticker"].astype(str).str.strip().str.upper()
                clean["portfolio"] = (
                    clean["portfolio"].fillna("").astype(str).str.strip()
                    .replace("", "Default")
                )
                clean = clean[
                    clean["ticker"].notna()
                    & (clean["ticker"].str.len() > 0)
                    & (clean["ticker"] != "NAN")
                ]
                save_holdings(clean)
                st.cache_data.clear()
                st.success("✅ Saved!")
                saved = True

        with col_dl:
            st.download_button(
                "⬇ Export",
                data=holdings.to_csv(index=False).encode(),
                file_name="holdings.csv",
                mime="text/csv",
                use_container_width=True,
            )

        if saved:
            st.rerun()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    prices_df, price_file, price_date = load_prices()
    holdings = load_holdings()

    render_sidebar(holdings, price_file, price_date)

    st.title("📈 Investment Portfolio Dashboard")
    st.caption(
        f"Today: **{date.today().strftime('%B %d, %Y')}**  •  "
        f"Price source: `{price_file or 'None'}`"
    )

    if holdings.empty:
        st.info("👈 No holdings yet — add positions in the sidebar.")
        return

    portfolios = sorted(holdings["portfolio"].dropna().unique().tolist())
    port_all   = build_portfolio(holdings, prices_df)   # all portfolios combined

    if port_all.empty:
        st.warning("All rows have zero shares — check your holdings data.")
        return

    # ── Tabs: All Portfolios + one tab per named portfolio ────────────────────
    tab_labels = ["📊 All Portfolios"] + [f"📁 {p}" for p in portfolios]
    tabs       = st.tabs(tab_labels)

    # ── All Portfolios tab ────────────────────────────────────────────────────
    with tabs[0]:
        if len(portfolios) > 1:
            st.subheader("📂 Portfolio Breakdown")
            summ = portfolio_summary(port_all)
            st.dataframe(
                style_summary(summ),
                use_container_width=True,
                hide_index=True,
                height=50 + 35 * len(summ),
            )
            st.markdown("---")

        # show_portfolio=True only when there is more than one portfolio
        render_view(
            port_all,
            show_portfolio=len(portfolios) > 1,
            key_suffix="all",
        )

    # ── Per-portfolio tabs ────────────────────────────────────────────────────
    for i, pf in enumerate(portfolios):
        with tabs[i + 1]:
            port_pf = build_portfolio(holdings, prices_df, portfolio_filter=pf)
            render_view(port_pf, show_portfolio=False, key_suffix=f"pf_{i}")


if __name__ == "__main__":
    main()
